//AUTH
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_RESET_USER = 'AUTH_RESET_USER';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

//MESSAGES
export const MESSAGES_SET_ERROR_LOGIN = 'MESSAGES_SET_ERROR_LOGIN';
export const MESSAGES_SET_ERROR_REGISTER = 'MESSAGES_SET_ERROR_REGISTER';
export const MESSAGES_SET_ERROR_MAP = 'MESSAGES_SET_ERROR_MAP';

//CONTEXT
export const CONTEXT_SET_LOADING = 'CONTEXT_SET_LOADING';
export const CONTEXT_SET_MAP = 'CONTEXT_SET_MAP';

//CLIENTS
export const CLIENTS_GET_DATA = 'CLIENTS_GET_DATA';

//MAP
export const MAP_GET_POSITION = 'MAP_GET_POSITION';
export const MAP_SET_ADDRESS = 'MAP_SET_ADDRESS';
